### ISSUE TITLE
Too high 150 mm rocket speed and tracking

### ISSUE THREAD

**Issue by Politary** [B-iggy/HWS-Configs#2]
Referring to this change
- Nerfed couple of Homing Speed values to make dodging more meaningful

Projectile speed on 150 mm CV rockets is too high to react to them and tracking is too big to dodge shots consistently.
Also it seems that high projectile speed makes lagshots more common. Just got 2 lagshots in a row in SP creative, it didn't happen with base game config. I think it should be made much lower for better gameplay.

**Comment by B-iggy** [comment]
>  Just got 2 lagshots in a row in SP creative, it didn't happen with base game config.
Watt? Technically there is and will never be a "lagshot" in Singleplayer 🙄 What you mean is called "BlastDamage" I guess.

Even IF then I request a video from it, please!!
The Dev would love to see that and "fix" it.

Will check the rest out.

**Comment by B-iggy** [comment]
I realized your feedback in https://github.com/B-iggy/HWS-Configs/commit/8c87c4f86aade7298f5a0683dcdba8956a3c39df

However I will close this issue first if I see a "lagshot" video in SP. If you can't provide it, let me know of course.

Couple of notes because you are hugging vanilla so much:
1. the 150mm rocket is shared by the CV Rocket Launcher (manual weapon) and the CV Rocket Turrets. Changing values for it, will change both items.
2. Because I want to boost CV dogfights, they have still a slight faster speed than vanilla
3. Because of the "invisible device SV meta", there is a reason why CV Rockets are faster than vanilla

**Comment by B-iggy** [comment]
Such claims bother me a lot and I can't sleep then.

I created only because of your claim a separate branch here:
https://github.com/B-iggy/HWS-Configs/commit/6a918013711f09211e5d7c54a68cf29a6b8aef7b

Checkout the "speed-lagshot" branch please, it only contains projectile speed changes to the one from Vanilla.

So make dedicated, video proofed tests please between the HWS-13 branch = high speed and this vanilla speed branch!

**Comment by B-iggy** [comment]
![image](https://user-images.githubusercontent.com/7815434/89253023-b6597b00-d61b-11ea-93ab-bcd044ce2b2d.png)

**Comment by B-iggy** [comment]
Ok thanks, verified and under investigation for a change 😕
